### ISSUE TITLE
🍉🍉文明吃瓜，实名围观。 微信群限时开放

### ISSUE THREAD

**Issue by Lax** [openbilibili/go-common#1054]
吃瓜一时爽，一直吃瓜。。。

本群仅用于学习目的，文明吃瓜，实名围观。
请勿传播非法信息

![WechatIMG121](https://user-images.githubusercontent.com/153937/56493293-363ffc80-6521-11e9-8020-deb1b60cd9ce.jpeg)

**Comment by Duanxs** [comment]
只能邀请了。。。

**Comment by Lax** [comment]
更新临时邀请码了，进群加群主 @Duanxs
